events {
    worker_connections 1024;
}

http {
    client_max_body_size 50M;

    upstream app_frontend {
        server frontend:5173;
        
    }

    upstream api_users {
        server ms-users-1:3000;
        server ms-users-2:3000;
    }
    
    upstream api_posts {
        server ms-posts-1:3000;
        server ms-posts-2:3000;
    }
    
    upstream api_likes {
        server ms-likes-1:3000;
        server ms-likes-2:3000;
    }
    
    upstream api_buscar {
        server ms-buscar-1:3000;
        server ms-buscar-2:3000;
    }

    upstream media_servers {
    server ms-media-1:3000;
    server ms-media-2:3000;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://api_users/;
        }

        location /api/posts/ {
            proxy_pass http://api_posts/;
        }

        location /api/likes/ {
            proxy_pass http://api_likes/;
        }

        location /api/buscar/ {
            proxy_pass http://api_buscar/;
        }

        location / {
            proxy_pass http://app_frontend/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location /api/media/ {
        proxy_pass http://media_servers/;
        }
    }
}